import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const venueInfo = [
    {
        id: 17,
        address: "1 Brewers Way",
        city: "Milwaukee",
        state: "WI",
        country: "USA",
        latitude: 43.028333,
        longitude: -87.971111,
    },
    {
        id: 30,
        address: "2000 Gene Autry Way",
        city: "Anaheim",
        state: "CA",
        country: "USA",
        latitude: 33.800278,
        longitude: -117.882778,
    },
    {
        id: 32,
        address: "151 Speedway Boulevard",
        city: "Bristol",
        state: "TN",
        country: "USA",
        latitude: 36.5156,
        longitude: -82.2569,
    },
    {
        id: 12,
        address: "700 Clark Ave",
        city: "St. Louis",
        state: "MO",
        country: "USA",
        latitude: 38.6225,
        longitude: -90.193056,
    },
    {
        id: 14,
        address: "401 East Jefferson Street",
        city: "Phoenix",
        state: "AZ",
        country: "USA",
        latitude: 33.445278,
        longitude: -112.066944,
    },
    {
        id: 25,
        address: "41 Seaver Way",
        city: "Queens",
        state: "NY",
        country: "USA",
        latitude: 40.756944,
        longitude: -73.845833,
    },
    {
        id: 19,
        address: "One Citizens Bank Way",
        city: "Philadelphia",
        state: "PA",
        country: "USA",
        latitude: 39.905833,
        longitude: -75.166389,
    },
    {
        id: 22,
        address: "2100 Woodward Avenue",
        city: "Detroit",
        state: "MI",
        country: "USA",
        latitude: 42.339167,
        longitude: -83.048611,
    },
    {
        id: 26,
        address: "2001 Blake Street",
        city: "Denver",
        state: "CO",
        country: "USA",
        latitude: 39.756111,
        longitude: -104.994167,
    },
    {
        id: 7,
        address: "501 Crawford Street",
        city: "Houston",
        state: "TX",
        country: "USA",
        latitude: 29.756944,
        longitude: -95.355556,
    },
    {
        id: 13,
        address: "1000 Vin Scully Avenue",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        latitude: 34.073611,
        longitude: -118.24,
    },
    {
        id: 23,
        address: "4 Jersey Street",
        city: "Boston",
        state: "MA",
        country: "USA",
        latitude: 42.34625,
        longitude: -71.09775,
    },
    {
        id: 16,
        address: "1 Steinbrenner Drive",
        city: "Tampa",
        state: "FL",
        country: "USA",
        latitude: 27.980278,
        longitude: -82.506667,
    },
    {
        id: 4,
        address: "734 Stadium Drive",
        city: "Arlington",
        state: "TX",
        country: "USA",
        latitude: 32.747361,
        longitude: -97.084167,
    },
    {
        id: 8,
        address: "100 Joe Nuxhall Way",
        city: "Cincinnati",
        state: "OH",
        country: "USA",
        latitude: 39.0975,
        longitude: -84.506667,
    },
    {
        id: 33,
        address: "1700 W 4th St",
        city: "Williamsport",
        state: "PA",
        country: "USA",
        latitude: 41.242347,
        longitude: -77.047067,
    },
    {
        id: 6,
        address: "1 Royal Way",
        city: "Kansas City",
        state: "MO",
        country: "USA",
        latitude: 39.051389,
        longitude: -94.480556,
    },
    {
        id: 11,
        address: "501 Marlins Way",
        city: "Miami",
        state: "FL",
        country: "USA",
        latitude: 25.778056,
        longitude: -80.219722,
    },
    {
        id: 5,
        address: "1500 South Capitol Street SE",
        city: "Washington",
        state: "DC",
        country: "USA",
        latitude: 38.872778,
        longitude: -77.0075,
    },
    {
        id: 28,
        address: "24 Willie Mays Plaza",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        latitude: 37.778611,
        longitude: -122.389167,
    },
    {
        id: 18,
        address: "333 West Camden Street",
        city: "Baltimore",
        state: "MD",
        country: "USA",
        latitude: 39.283889,
        longitude: -76.621667,
    },
    {
        id: 9,
        address: "100 Park Blvd",
        city: "San Diego",
        state: "CA",
        country: "USA",
        latitude: 32.7073,
        longitude: -117.1566,
    },
    {
        id: 27,
        address: "115 Federal Street",
        city: "Pittsburgh",
        state: "PA",
        country: "USA",
        latitude: 40.446944,
        longitude: -80.005833,
    },
    {
        id: 31,
        address: "2401 Ontario Street",
        city: "Cleveland",
        state: "OH",
        country: "USA",
        latitude: 41.495833,
        longitude: -81.685278,
    },
    {
        id: 10,
        address: "333 West 35th Street",
        city: "Chicago",
        state: "IL",
        country: "USA",
        latitude: 41.83,
        longitude: -87.633889,
    },
    {
        id: 3,
        address: "1 Blue Jays Way",
        city: "Toronto",
        state: "ON",
        country: "CA",
        latitude: 43.641389,
        longitude: -79.389167,
    },
    {
        id: 20,
        address: "400 Ballpark Drive",
        city: "West Sacramento",
        state: "CA",
        country: "USA",
        latitude: 38.580372,
        longitude: -121.5138,
    },
    {
        id: 15,
        address: "1250 First Avenue South",
        city: "Seattle",
        state: "WA",
        country: "USA",
        latitude: 47.591,
        longitude: -122.333,
    },
    {
        id: 21,
        address: "1 Twins Way",
        city: "Minneapolis",
        state: "MN",
        country: "USA",
        latitude: 44.981667,
        longitude: -93.278333,
    },
    {
        id: 1,
        address: "1 Chome-3-61 Koraku",
        city: "Bunkyo City",
        state: "Tokyo",
        country: "JP",
        latitude: 35.7056,
        longitude: 139.7519,
    },
    {
        id: 29,
        address: "755 Battery Avenue SE",
        city: "Cumberland",
        state: "GA",
        country: "USA",
        latitude: 33.89,
        longitude: -84.468,
    },
    {
        id: 24,
        address: "1060 West Addison Street",
        city: "Chicago",
        state: "IL",
        country: "USA",
        latitude: 41.948056,
        longitude: -87.655556,
    },
    {
        id: 2,
        address: "1 East 161st Street",
        city: "Bronx",
        state: "NY",
        country: "USA",
        latitude: 40.829167,
        longitude: -73.926389,
    },
];

async function updateVenues() {
    try {
        const venues = await prisma.venue.findMany();

        for (const venue of venues) {
            const info = venueInfo.find((v) => v.id === venue.id);
            if (!info) {
                console.log(`No info found for venue with ID: ${venue.id}`);
                continue;
            }

            await prisma.venue.update({
                where: { id: venue.id },
                data: {
                    address: info.address,
                    city: info.city,
                    state: info.state,
                    country: info.country,
                    latitude: info.latitude,
                    longitude: info.longitude,
                },
            });

            console.log(`Updated venue: ${venue.name}.`);
        }
    } catch (error) {
        console.error("Error updating team pitching scores:", error);
    } finally {
        await prisma.$disconnect();
    }
}

updateVenues();
